# add stages here 
stages:
  load_data:
    cmd: python src\stage_02_load_data.py --config=params.yaml
    deps:
    - src\stage_01_get_data.py
    - src\stage_02_load_data.py
    - actual_data\Final_Train.xlsx
    outs:
    - data\raw\Final_Train.csv

  preprocess_data:
    cmd: python src\stage_03_preprocess_data.py --config=params.yaml
    deps:
    - src\stage_03_preprocess_data.py
    - data\raw\Final_Train.csv
    outs:
    - data\raw\processed_data.csv

  split_data:
    cmd: python src\stage_04_split_data.py --config=params.yaml
    deps:
    - src\stage_04_split_data.py
    - data\raw\processed_data.csv
    outs:
    - data\processed\train_Final.csv
    - data\processed\test_Final.csv

  train_and_evaluate:
    cmd: python src\stage_05_train_evaluate.py --config=params.yaml
    deps:
      - src\stage_05_train_evaluate.py
      - data\processed\train_Final.csv
      - data\processed\test_Final.csv
    params:
      - estimators.RandomForestRegressor.params.max_depth
      - estimators.RandomForestRegressor.params.min_samples_split
      - estimators.RandomForestRegressor.params.min_samples_leaf
      - estimators.RandomForestRegressor.params.n_estimators
    metrics:
      - reports\scores.json:
          cache: false
      - reports\params.json:
          cache: false
    outs:
      - saved_model\model.joblib

    
    