base:
  project: Doctor-Fees-Prediction
  target_col: Fees

data_source: 
  source: actual_data\Final_Train.xlsx

load_data:
  raw_data: data\raw\Final_Train.csv
  processed_data: data\raw\processed_data.csv

split_data: 
  train_data: data\processed\train_Final.csv
  test_data: data\processed\test_Final.csv
  split_ratio: 0.2
  random_state: 42

estimators:
  RandomForestRegressor:
    params:
      max_depth: 12
      n_estimators: 660
      min_samples_split: 10
      min_samples_leaf: 5

model_dir: saved_model

reports:
  params: reports\params.json
  scores: reports\scores.json

webapp_model_dir: 
  model: prediction_service/model/model.joblib
  